--student id: 30758017
--student name: ZIXIN HAO
-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-09-12 10:47:20 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

set echo on
spool prop_rental_schema_output.txt

DROP TABLE damage CASCADE CONSTRAINTS;

DROP TABLE maintenance CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE paid_by_method CASCADE CONSTRAINTS;

DROP TABLE payment CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE rent CASCADE CONSTRAINTS;

DROP TABLE tenant CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE damage (
    dam_no       NUMBER(7) NOT NULL,
    dam_prop_no  NUMBER(7) NOT NULL,
    dam_date     DATE NOT NULL,
    dam_time     DATE NOT NULL,
    dam_type     VARCHAR2(25 BYTE) NOT NULL,
    dam_cost     NUMBER NOT NULL,
    pay_no       NUMBER(7),
    rent_no      NUMBER(7) NOT NULL
);

COMMENT ON COLUMN damage.dam_no IS
    'damage number(surrogate PK)';

COMMENT ON COLUMN damage.dam_prop_no IS
    'damage property Number';

COMMENT ON COLUMN damage.dam_date IS
    'the date of damage';

COMMENT ON COLUMN damage.dam_time IS
    'the time of the damage';

COMMENT ON COLUMN damage.dam_type IS
    'the type of the damage';

COMMENT ON COLUMN damage.dam_cost IS
    'the cost of the damage';

COMMENT ON COLUMN damage.pay_no IS
    'payment number';

COMMENT ON COLUMN damage.rent_no IS
    'rent number';

CREATE UNIQUE INDEX damage__idx ON
    damage (
        pay_no
    ASC );

ALTER TABLE damage ADD CONSTRAINT damage_pk PRIMARY KEY ( dam_no );

ALTER TABLE damage
    ADD CONSTRAINT damage_nk UNIQUE ( dam_date,
                                      dam_time,
                                      dam_prop_no );

CREATE TABLE maintenance (
    prop_no         NUMBER(7) NOT NULL,
    maint_datetime  DATE NOT NULL,
    maint_cost      NUMBER NOT NULL,
    maint_desc      VARCHAR2(50 BYTE) NOT NULL,
    owner_no        NUMBER(7) NOT NULL
);

COMMENT ON COLUMN maintenance.prop_no IS
    'property number';

COMMENT ON COLUMN maintenance.maint_datetime IS
    'maintenance date';

COMMENT ON COLUMN maintenance.maint_cost IS
    'maintenance cost';

COMMENT ON COLUMN maintenance.maint_desc IS
    'maintenance describe';

COMMENT ON COLUMN maintenance.owner_no IS
    'owner number';

ALTER TABLE maintenance ADD CONSTRAINT maintenance_pk PRIMARY KEY ( prop_no,
                                                                    maint_datetime );

CREATE TABLE owner (
    owner_no           NUMBER(7) NOT NULL,
    owner_title        VARCHAR2(20 BYTE) NOT NULL,
    owner_gname        VARCHAR2(15 BYTE) NOT NULL,
    owner_fname        VARCHAR2(15 BYTE) NOT NULL,
    owner_ad_street    VARCHAR2(20 BYTE) NOT NULL,
    owner_ad_city      VARCHAR2(20 BYTE) NOT NULL,
    owner_ad_state     VARCHAR2(20 BYTE) NOT NULL,
    owner_ad_postcode  VARCHAR2(4 BYTE) NOT NULL
);

COMMENT ON COLUMN owner.owner_no IS
    'owner number';

COMMENT ON COLUMN owner.owner_title IS
    'owner''s title';

COMMENT ON COLUMN owner.owner_gname IS
    'owner''s given name';

COMMENT ON COLUMN owner.owner_fname IS
    'owner''s family name';

COMMENT ON COLUMN owner.owner_ad_street IS
    'owner_address_street';

COMMENT ON COLUMN owner.owner_ad_city IS
    'owner_address_city';

COMMENT ON COLUMN owner.owner_ad_state IS
    'owner_address_state';

COMMENT ON COLUMN owner.owner_ad_postcode IS
    'owner_address_postcode';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_no );

CREATE TABLE paid_by_method (
    paymet_id    NUMBER(7) NOT NULL,
    paymet_name  VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN paid_by_method.paymet_id IS
    'pay method ID';

COMMENT ON COLUMN paid_by_method.paymet_name IS
    'name of payment methods';

ALTER TABLE paid_by_method ADD CONSTRAINT paid_by_method_pk PRIMARY KEY ( paymet_id );

CREATE TABLE payment (
    pay_no      NUMBER(7) NOT NULL,
    pay_date    DATE NOT NULL,
    pay_time    DATE NOT NULL,
    pay_type    VARCHAR2(10 BYTE) NOT NULL,
    pay_amount  NUMBER NOT NULL,
    paymet_id   NUMBER(7) NOT NULL,
    rent_no     NUMBER(7) NOT NULL
);

ALTER TABLE payment
    ADD CONSTRAINT chk_payment_type CHECK ( pay_type IN ( 'B', 'D', 'R' ) );

COMMENT ON COLUMN payment.pay_no IS
    'payment number';

COMMENT ON COLUMN payment.pay_date IS
    'payment date';

COMMENT ON COLUMN payment.pay_time IS
    'payment time';

COMMENT ON COLUMN payment.pay_type IS
    'payment type';

COMMENT ON COLUMN payment.pay_amount IS
    'the amount of payment';

COMMENT ON COLUMN payment.paymet_id IS
    'pay method ID';

COMMENT ON COLUMN payment.rent_no IS
    'rent number';

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( pay_no );

CREATE TABLE property (
    prop_no           NUMBER(7) NOT NULL,
    prop_ad_street    VARCHAR2(15 BYTE) NOT NULL,
    prop_ad_city      VARCHAR2(15 BYTE) NOT NULL,
    prop_ad_state     VARCHAR2(15 BYTE) NOT NULL,
    prop_ad_postcode  VARCHAR2(15 BYTE) NOT NULL,
    prop_value        NUMBER(4) NOT NULL,
    owner_no          NUMBER(7) NOT NULL
);

COMMENT ON COLUMN property.prop_no IS
    'property number';

COMMENT ON COLUMN property.prop_ad_street IS
    'property address street';

COMMENT ON COLUMN property.prop_ad_city IS
    'property address city';

COMMENT ON COLUMN property.prop_ad_state IS
    'property address state';

COMMENT ON COLUMN property.prop_ad_postcode IS
    'property address postcode';

COMMENT ON COLUMN property.prop_value IS
    'property value';

COMMENT ON COLUMN property.owner_no IS
    'owner number';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( prop_no );

CREATE TABLE rent (
    rent_no               NUMBER(7) NOT NULL,
    prop_no               NUMBER(7) NOT NULL,
    rent_lease_startdate  DATE NOT NULL,
    rent_bond             NUMBER NOT NULL,
    rent_lease_period     VARCHAR2(10 BYTE) NOT NULL,
    rent_weekly_rate      NUMBER,
    tenant_no             NUMBER(7) NOT NULL
);

COMMENT ON COLUMN rent.rent_no IS
    'rent number';

COMMENT ON COLUMN rent.prop_no IS
    'property number';

COMMENT ON COLUMN rent.rent_lease_startdate IS
    'the start date of rent lease';

COMMENT ON COLUMN rent.rent_bond IS
    'rent bond';

COMMENT ON COLUMN rent.rent_lease_period IS
    'period of rent lease';

COMMENT ON COLUMN rent.rent_weekly_rate IS
    'rent weekly rate';

COMMENT ON COLUMN rent.tenant_no IS
    'tenant number';

ALTER TABLE rent ADD CONSTRAINT rent_pk PRIMARY KEY ( rent_no );

ALTER TABLE rent ADD CONSTRAINT rent_nk UNIQUE ( rent_lease_startdate,
                                                 prop_no );

CREATE TABLE tenant (
    tenant_no         NUMBER(7) NOT NULL,
    tenant_title      VARCHAR2(20 BYTE) NOT NULL,
    tenant_fname      VARCHAR2(20 BYTE),
    tenant_gname      VARCHAR2(20 BYTE),
    tenant_ad_street  VARCHAR2(20 BYTE) NOT NULL,
    tenant_ad_city    VARCHAR2(20 BYTE) NOT NULL,
    tenant_ad_state   VARCHAR2(20 BYTE) NOT NULL,
    tenant_ad_pcode   CHAR(4 BYTE) NOT NULL,
    tenant_phone      CHAR(9 BYTE) NOT NULL
);

COMMENT ON COLUMN tenant.tenant_no IS
    'tenant number';

COMMENT ON COLUMN tenant.tenant_title IS
    'tenant title';

COMMENT ON COLUMN tenant.tenant_fname IS
    'tenant family name';

COMMENT ON COLUMN tenant.tenant_gname IS
    'tenant given name';

COMMENT ON COLUMN tenant.tenant_ad_street IS
    'tenant address - street';

COMMENT ON COLUMN tenant.tenant_ad_city IS
    'tenant address - city';

COMMENT ON COLUMN tenant.tenant_ad_state IS
    'tenant_ad_state';

COMMENT ON COLUMN tenant.tenant_ad_pcode IS
    'tenant address - postcode';

COMMENT ON COLUMN tenant.tenant_phone IS
    'tenant phone number';

ALTER TABLE tenant ADD CONSTRAINT tenant_pk PRIMARY KEY ( tenant_no );

ALTER TABLE damage
    ADD CONSTRAINT damage_payment FOREIGN KEY ( pay_no )
        REFERENCES payment ( pay_no );

ALTER TABLE maintenance
    ADD CONSTRAINT owner_maintenance FOREIGN KEY ( owner_no )
        REFERENCES owner ( owner_no );

ALTER TABLE property
    ADD CONSTRAINT owner_property FOREIGN KEY ( owner_no )
        REFERENCES owner ( owner_no );

ALTER TABLE payment
    ADD CONSTRAINT payment_paid_by_method FOREIGN KEY ( paymet_id )
        REFERENCES paid_by_method ( paymet_id );

ALTER TABLE maintenance
    ADD CONSTRAINT property_maintenance FOREIGN KEY ( prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE rent
    ADD CONSTRAINT property_rent FOREIGN KEY ( prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE damage
    ADD CONSTRAINT rent_damage FOREIGN KEY ( rent_no )
        REFERENCES rent ( rent_no );

ALTER TABLE payment
    ADD CONSTRAINT rent_payment FOREIGN KEY ( rent_no )
        REFERENCES rent ( rent_no );

ALTER TABLE rent
    ADD CONSTRAINT tenant_rent FOREIGN KEY ( tenant_no )
        REFERENCES tenant ( tenant_no );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
spool off
set echo off