/*ZIXIN HAO 30758017
#TUTORIAL_Number:05*/

CREATE TABLE TEAM
(
team_no NUMERIC(3),
emp_no NUMERIC(5),
CONSTRAINT pk_team PRIMARY KEY (team_no)

);

CREATE TABLE EMPLOYEE
(
emp_no NUMERIC(5),
emp_fname VARCHAR(30),
emp_lname VARCHAR(30),
emp_street VARCHAR(50) NOT NULL,
emp_town VARCHAR(30) NOT NULL,
emp_pcode CHAR(4) NOT NULL,
emp_dob DATE NOT NULL,
emp_taxno VARCHAR(20),
team_no NUMERIC(3),
mentor_no NUMERIC(5),
CONSTRAINT pk_EMPLOYEE PRIMARY KEY (emp_no)
);

ALTER TABLE TEAM 
ADD(
    CONSTRAINT fk_TEAM FOREIGN KEY (emp_no) REFERENCES EMPLOYEE (emp_no) ON DELETE SET NULL   
);
ALTER TABLE EMPLOYEE 
ADD(
    CONSTRAINT fk_EMPLOYEE_team FOREIGN KEY (team_no) REFERENCES TEAM (team_no) ON DELETE SET NULL,
    CONSTRAINT fk_EMPLOYEE_self FOREIGN KEY (mentor_no) REFERENCES EMPLOYEE (emp_no) ON DELETE SET NULL
);









